#!/bin/bash
set -e

if [ "$1" == "-unit" ]; then
    TARGET_UNIT=$2
fi

write_env() {
    if [ $1 == "" ]; then
        echo "bad args"
        exit 1
    fi
    touch $HOME/.zshrc
    gsed -i /${1}-start/,/${1}-end/d $HOME/.zshrc
    cat >>$HOME/.zshrc <<EOF
# ${1}-start
$(< /dev/stdin)
# ${1}-end
EOF
}

for UNIT_FILE in units/*.sh; do
    UNIT=${UNIT_FILE#units/}
    UNIT=${UNIT%.sh}
    if [ -z "$TARGET_UNIT" -o "$UNIT" == "$TARGET_UNIT" ]; then
        echo "== Running unit ${UNIT} ==========================="
        . $UNIT_FILE
        echo "== Unit ${UNIT} completed ========================="
    fi
done

# Link static files.
FILES=(
    .gitconfig
    .gitprompt
    .ssh/config
    .config/nvim
    .local/share/nvim
)
for FILE in ${FILES[@]}; do
    LINK=$HOME/$FILE
    TARGET=$PWD/$FILE
    if [[ ! -d $(dirname $LINK) ]]; then
        mkdir -p $(dirname $LINK)
    fi
    if [[ -L $LINK ]]; then
        echo "==> update $LINK"
        unlink $LINK
    else
        echo "==> create $LINK"
    fi
    ln -s $TARGET $LINK
done

# Fetch submodules.
git submodule init
git submodule update
