#!/bin/bash

FILES=(
    .gitconfig
    .gitprompt
    .inputrc
    .screenrc
    .shellenv
    .ssh/config
    .config/nvim
    .tmux.conf
)

function link() {
    while [[ $# -gt 0 ]]; do
        LINK=$HOME/$1
        TARGET=$PWD/$1
        shift
        if [[ ! -d $(dirname $LINK) ]]; then
            mkdir -p $(dirname $LINK)
        fi
        if [[ -L $LINK ]]; then
            echo "==> update $LINK"
            unlink $LINK
        else
            echo "==> create $LINK"
        fi
        ln -s $TARGET $LINK
    done
}

link ${FILES[@]}
